export { default as Navbar } from "../Container/Navbar/Navbar.jsx"
export { default as Header } from "../Container/Header/Header.jsx"
export { default as About } from "../Container/About/About.jsx"
export { default as Services } from "../Container/Services/Services.jsx"
export { default as Portfolio } from "../Container/Portfolio/Portfolio.jsx"
export { default as Team } from "../Container/Team/Team.jsx"
export { default as Contact } from "../Container/Contact/Contact.jsx"
export { default as Footer } from "../Container/Footer/Footer.jsx"